version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      berichte:
    # volumes:
    #   - .:/usr/src/app
    #   - /usr/src/app/node_modules

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      berichte:
    # volumes:
    #   - ./client:/usr/src/app
    #   - /usr/src/app/node_modules

networks:
  berichte:
